import numpy as np
l=[1,2,3,4,5,6]
a=np.asarray(l,dtype=int)
print(a)
print("Matrix creation")
b=a.reshape(2,3)
print(b)
print("shape")
print(b.shape)
print("sequence of 24 nos")
c = np.arange(24)
print(c)
print("matrix of ones")
d=np.ones([3,3],dtype=int)
print(d)
print("sequence from 10to 20 with step-2")
x = np.arange(10,20,2)
print(x)
y = np.arange(10)
print("slicing")
z = slice(2,7,2)
print(y[z])
e = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(e)
# slice items starting from index
print('Now we will slice the array from the index a[1:]')
print(e[1:])
print("broadcasting")
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
c = a * b
print(c)
a = np.arange(9)

print('First array:')
print(a)
print('\n')

print('Split the array in 3 equal-sized subarrays:')
b = np.split(a,3)
print(b)
print("string lower")
print(np.char.lower(['HELLO','WORLD']))
print(np.char.lower('HELLO'))
print(np.char.splitlines('hello\nhow are you?'))
a = np.array([[3,7,5],[8,4,3],[2,4,9]])

print('Our array is:')
print(a )
print('\n')

print('Applying amin() function:')
print(np.amin(a,1))
print('\n' )

print('Applying amin() function again:')
print(np.amin(a,0))
print('\n')